### 사망 신고 API 등록
POST http://localhost:8080/residents/3/death
Content-Type: application/json
Accept: application/json

{
  "deathReportDate": "20200502",
  "targetResident": {
    "name" : "남석환",
    "residentRegistrationNumber" : "540514-1234562",
    "deathDate" : "20210429090300",
    "deathPlaceCode" : "주택",
    "deathPlaceAddress" : "강원도 고성군 금강산로 290번길"
  },
  "reportResident": {
    "name" : "박한나",
    "residentRegistrationNumber" : "551022-1234563",
    "deathBirthReportQualificationsCode": "동거친족",
    "emailAddress": "nam@nhnad.co.kr",
    "phoneNumber": "010-1234-5678"
  }
}

### 사망 신고 API 수정
PUT http://localhost:8080/residents/2/death/1
Content-Type: application/json
Accept: application/json

{
  "deathReportDate": "20200502",
  "targetResident": {
    "name" : "남길동",
    "residentRegistrationNumber" : "130914-1234561",
    "deathDate" : "20210429090300",
    "deathPlaceCode" : "병원",
    "deathPlaceAddress" : "강원도 고성군 금강산로 290번길"
  },
  "reportResident": {
    "name" : "남석환",
    "residentRegistrationNumber" : "540514-1234562",
    "deathBirthReportQualificationsCode": "비동거친족",
    "emailAddress": "nam@nhnad.co.kr",
    "phoneNumber": "010-1234-5678"
  }
}

### 사망 신고 API 삭제
DELETE http://localhost:8080/residents/2/death/1
Content-Type: application/json
Accept: application/json