### 출생신고서 등록 POST /residents/{serialNumber}/birth
POST http://localhost:8080/residents/4/birth
Content-Type: application/json
Accept: application/json

{
  "birthReportDate": "19790510",
  "targetResident": {
    "name" : "남기호",
    "genderCode" : "남",
    "birthDate" : "20120315145900",
    "birthPlaceCode" : "병원",
    "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
  },
  "fatherResident":  {
    "name" : "남기준",
    "residentRegistrationNumber" : "790510-1234564"
  },
  "motherResident": {
    "name" : "이주은",
    "residentRegistrationNumber" : "820821-1234565"
  },
  "reportResident": {
    "name" : "남기준",
    "residentRegistrationNumber" : "130914-1234561",
    "reportQualificationsCode": "부",
    "emailAddress": "nam@nhnad.co.kr",
    "phoneNumber": "010-1234-5678"
  }
}

### 출생신고서 수정 PUT /residents/{serialNumber}/birth/{targetSerialNumber}
PUT http://localhost:8080/residents/4/birth/7
Content-Type: application/json
Accept: application/json

{
  "birthReportDate": "19790510",
  "targetResident": {
    "name" : "남기미",
    "genderCode" : "여",
    "birthDate" : "20120315145900",
    "birthPlaceCode" : "병원",
    "registrationBaseAddress" : "경기도 성남시 분당구 대왕판교로645번길"
  },
  "fatherResident":  {
    "name" : "남기준",
    "residentRegistrationNumber" : "790510-1234564"
  },
  "motherResident": {
    "name" : "이주은",
    "residentRegistrationNumber" : "820821-1234565"
  },
  "reportResident": {
    "name" : "남기준",
    "residentRegistrationNumber" : "130914-1234561",
    "reportQualificationsCode": "부",
    "emailAddress": "nam2@nhnad.co.kr",
    "phoneNumber": "011-1234-5678"
  }
}

### 출생신고서 삭제 DELETE /residents/{serialNumber}/birth/{targetSerialNumber}
DELETE http://localhost:8080/residents/4/birth/7
Content-Type: application/json
Accept: application/json